"""domain_models

Revision ID: d89380b75034
Revises: a9d195f06e3f
Create Date: 2026-04-10 21:09:19.807837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd89380b75034'
down_revision: Union[str, Sequence[str], None] = 'a9d195f06e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('whatsapp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sa.Enum('TECNICO', 'ASESOR', 'JEFE_TALLER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('vehicle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('placa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kilometraje', sa.Integer(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_vehicle_placa'), 'vehicle', ['placa'], unique=True)
    op.create_table('appointment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('bloque_horario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', name='appointmentestado'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('RECEPCION', 'DIAGNOSTICO', 'APROBACION', 'REPARACION', 'QC', 'ENTREGA', 'CERRADA', name='orderstatus'), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=True),
    sa.Column('kilometraje_ingreso', sa.Integer(), nullable=True),
    sa.Column('kilometraje_salida', sa.Integer(), nullable=True),
    sa.Column('motivo_ingreso', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('accion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detalle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dispositivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['service_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damage_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('foto_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reconocido_por_cliente', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['service_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostic_finding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=False),
    sa.Column('motivo_ingreso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tiempo_estimado', sa.Float(), nullable=True),
    sa.Column('fotos', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('es_hallazgo_adicional', sa.Boolean(), nullable=False),
    sa.Column('es_critico_seguridad', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['service_order.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'CREDITO', name='metodopago'), nullable=False),
    sa.Column('es_credito', sa.Boolean(), nullable=False),
    sa.Column('saldo_pendiente', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['service_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('nps_survey',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('atencion', sa.Integer(), nullable=False),
    sa.Column('instalaciones', sa.Integer(), nullable=False),
    sa.Column('tiempos', sa.Integer(), nullable=False),
    sa.Column('precios', sa.Integer(), nullable=False),
    sa.Column('recomendacion', sa.Integer(), nullable=False),
    sa.Column('comentarios', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['service_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('perimeter_photo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('angulo', sa.Enum('FRONTAL', 'TRASERO', 'IZQUIERDO', 'DERECHO', name='angulofoto'), nullable=False),
    sa.Column('foto_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['service_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_check',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('inspector_id', sa.Uuid(), nullable=False),
    sa.Column('items_verificados', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kilometraje_salida', sa.Integer(), nullable=True),
    sa.Column('nivel_aceite_salida', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nivel_refrigerante_salida', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nivel_frenos_salida', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['service_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('quotation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('impuestos', sa.Float(), nullable=False),
    sa.Column('shop_supplies', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADA', 'RECHAZADA', name='quotationestado'), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['service_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reception_checklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('nivel_aceite', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nivel_refrigerante', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nivel_frenos', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llanta_repuesto', sa.Boolean(), nullable=False),
    sa.Column('kit_carretera', sa.Boolean(), nullable=False),
    sa.Column('botiquin', sa.Boolean(), nullable=False),
    sa.Column('extintor', sa.Boolean(), nullable=False),
    sa.Column('documentos_recibidos', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('firma_cliente_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['service_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('part',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origen', sa.Enum('STOCK', 'PEDIDO', name='partorigen'), nullable=False),
    sa.Column('costo', sa.Float(), nullable=False),
    sa.Column('margen', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('proveedor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['diagnostic_finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotation_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mano_obra', sa.Float(), nullable=False),
    sa.Column('costo_repuesto', sa.Float(), nullable=False),
    sa.Column('precio_final', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['diagnostic_finding.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_item')
    op.drop_table('part')
    op.drop_table('reception_checklist')
    op.drop_table('quotation')
    op.drop_table('quality_check')
    op.drop_table('perimeter_photo')
    op.drop_table('nps_survey')
    op.drop_table('invoice')
    op.drop_table('diagnostic_finding')
    op.drop_table('damage_record')
    op.drop_table('audit_log')
    op.drop_table('service_order')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_vehicle_placa'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('customer')
    # ### end Alembic commands ###
